[package]
authors = ["Caleb Taylor <caleb89taylor@gmail.com>"]
edition = "2018"
name = "chess-engine"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4"
bevy_mod_picking = "0.3.0"
